build:
  environment:
    php:
      version: 5.6.9
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=clover.xml'
        coverage:
          file: 'clover.xml'
          format: 'php-clover'
checks:
  php:
    code_rating: true
    duplication: true
