build:
  environment:
    php:
      version: 5.6.9
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=coverage.clover'
        coverage:
          file: 'coverage.clover'
          format: 'php-clover'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

checks:
  php:
    code_rating: true
    duplication: true
