language: php

php:
  - 5.6

before_script:
  - composer install --dev --prefer-source --no-interaction
  - composer dumpautoload

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
