language: php

php:
  - 7.1

env:
  - DB_HOST=127.0.0.1

before_script:
  - mysql -e "CREATE DATABASE kubikvest CHARACTER SET utf8 COLLATE utf8_general_ci"
  - cat sql/kubikvest.sql | mysql kubikvest
  - composer install --prefer-source --no-interaction
  - composer dumpautoload

script:
  - mkdir -p build/logs
  - phpunit --stop-on-failure --coverage-text --coverage-clover=coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

notifications:
  slack: kubikvest:vzWICu78pcBH0EKby2tbJSwW
